### ISSUE TITLE
 Specify PageDirectoryBase (DTB/CR3) in -dtb option if value if known.

### ISSUE THREAD

**Issue by Sigma12456** [ufrisk/LeechCore#40]
I have a windows 11 amd system and i am frequently experiencing an issue where my dma just stops working till I restart my main system. I already am using a memmap which is called mmap.txt and is correct(verified it manually) :/

 Specify PageDirectoryBase (DTB/CR3) in -dtb option if value if known.

**Comment by ufrisk** [comment]
This happens if DMA is no longer working for some reason.

The most common reason would be an out of bounds read, which is usually corrected with a memory map (which you mention you use so it's a bit strange if it's correct). In some cases some custom firmwares have been seen to cause issues as well. It's really hard for me to say what the exact issue is in your case.

You can check if DMA is still working with: `pcileech.exe -device fpga -v display -min 0x1000`

Best would probably be to hop into the Discord server to ask further questions if you don't get it to work.

<a href="https://discord.gg/pcileech"><img src="https://discord.com/api/guilds/1155439643395883128/widget.png?style=banner3"/></a>
